name: .NET Core 7.0 Restful Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted                

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build docker image
      run: docker build -f Dockerfile -t weather-service:latest .

    - name: Up docker container
      run: docker run --name=weather-service -p 8080:80  -d weather-service:latest
